namespace ModernCSharp.Generators;

// A plain class: records would need IsExternalInit, which netstandard2.0 lacks.
sealed class Polyfill {
    public Polyfill(string @namespace, string name, string body) {
        Namespace = @namespace;
        Name = name;
        Body = body;
    }

    public string Namespace { get; }

    public string Name { get; }

    public string Body { get; }

    public string MetadataName => $"{Namespace}.{Name}";

    // Block namespaces: the generated code must compile with -langversion:9 too.
    public string Source => $$"""
        // <auto-generated/>
        #nullable enable

        namespace {{Namespace}}
        {
        {{Body}}
        }

        """;
}

static class Polyfills {
    const string CompilerServices = "System.Runtime.CompilerServices";
    const string CodeAnalysis = "System.Diagnostics.CodeAnalysis";

    public static readonly Polyfill[] All = {
        // C# 9 `init` accessors and `record` types.
        new(CompilerServices, "IsExternalInit", """
                internal static class IsExternalInit { }
            """),

        // C# 10 [CallerArgumentExpression].
        new(CompilerServices, "CallerArgumentExpressionAttribute", """
                [global::System.AttributeUsage(global::System.AttributeTargets.Parameter, AllowMultiple = false, Inherited = false)]
                internal sealed class CallerArgumentExpressionAttribute : global::System.Attribute
                {
                    public CallerArgumentExpressionAttribute(string parameterName)
                    {
                        ParameterName = parameterName;
                    }

                    public string ParameterName { get; }
                }
            """),

        // C# 10 custom interpolated string handlers.
        new(CompilerServices, "InterpolatedStringHandlerAttribute", """
                [global::System.AttributeUsage(global::System.AttributeTargets.Class | global::System.AttributeTargets.Struct, AllowMultiple = false, Inherited = false)]
                internal sealed class InterpolatedStringHandlerAttribute : global::System.Attribute
                {
                }
            """),

        new(CompilerServices, "InterpolatedStringHandlerArgumentAttribute", """
                [global::System.AttributeUsage(global::System.AttributeTargets.Parameter, AllowMultiple = false, Inherited = false)]
                internal sealed class InterpolatedStringHandlerArgumentAttribute : global::System.Attribute
                {
                    public InterpolatedStringHandlerArgumentAttribute(string argument)
                    {
                        Arguments = new[] { argument };
                    }

                    public InterpolatedStringHandlerArgumentAttribute(params string[] arguments)
                    {
                        Arguments = arguments;
                    }

                    public string[] Arguments { get; }
                }
            """),

        // C# 11 `required` members.
        new(CompilerServices, "RequiredMemberAttribute", """
                [global::System.AttributeUsage(global::System.AttributeTargets.Class | global::System.AttributeTargets.Struct | global::System.AttributeTargets.Field | global::System.AttributeTargets.Property, AllowMultiple = false, Inherited = false)]
                internal sealed class RequiredMemberAttribute : global::System.Attribute
                {
                }
            """),

        new(CompilerServices, "CompilerFeatureRequiredAttribute", """
                [global::System.AttributeUsage(global::System.AttributeTargets.All, AllowMultiple = true, Inherited = false)]
                internal sealed class CompilerFeatureRequiredAttribute : global::System.Attribute
                {
                    public const string RefStructs = nameof(RefStructs);
                    public const string RequiredMembers = nameof(RequiredMembers);

                    public CompilerFeatureRequiredAttribute(string featureName)
                    {
                        FeatureName = featureName;
                    }

                    public string FeatureName { get; }

                    public bool IsOptional { get; set; }
                }
            """),

        new(CodeAnalysis, "SetsRequiredMembersAttribute", """
                [global::System.AttributeUsage(global::System.AttributeTargets.Constructor, AllowMultiple = false, Inherited = false)]
                internal sealed class SetsRequiredMembersAttribute : global::System.Attribute
                {
                }
            """),

        // C# 11 ref safety rules.
        new(CodeAnalysis, "UnscopedRefAttribute", """
                [global::System.AttributeUsage(global::System.AttributeTargets.Method | global::System.AttributeTargets.Property | global::System.AttributeTargets.Parameter, AllowMultiple = false, Inherited = false)]
                internal sealed class UnscopedRefAttribute : global::System.Attribute
                {
                }
            """),

        // C# 12 collection expressions on custom collection types.
        new(CompilerServices, "CollectionBuilderAttribute", """
                [global::System.AttributeUsage(global::System.AttributeTargets.Class | global::System.AttributeTargets.Struct | global::System.AttributeTargets.Interface, Inherited = false)]
                internal sealed class CollectionBuilderAttribute : global::System.Attribute
                {
                    public CollectionBuilderAttribute(global::System.Type builderType, string methodName)
                    {
                        BuilderType = builderType;
                        MethodName = methodName;
                    }

                    public global::System.Type BuilderType { get; }

                    public string MethodName { get; }
                }
            """),

        // C# 12 [Experimental].
        new(CodeAnalysis, "ExperimentalAttribute", """
                [global::System.AttributeUsage(
                    global::System.AttributeTargets.Assembly | global::System.AttributeTargets.Module | global::System.AttributeTargets.Class | global::System.AttributeTargets.Struct |
                    global::System.AttributeTargets.Enum | global::System.AttributeTargets.Constructor | global::System.AttributeTargets.Method | global::System.AttributeTargets.Property |
                    global::System.AttributeTargets.Field | global::System.AttributeTargets.Event | global::System.AttributeTargets.Interface | global::System.AttributeTargets.Delegate,
                    Inherited = false)]
                internal sealed class ExperimentalAttribute : global::System.Attribute
                {
                    public ExperimentalAttribute(string diagnosticId)
                    {
                        DiagnosticId = diagnosticId;
                    }

                    public string DiagnosticId { get; }

                    public string? UrlFormat { get; set; }
                }
            """),
    };
}
